name: Quarto Build

on: # either one of the following three cases  
  workflow_dispatch: # manually trigger

  schedule:
    - cron: '0 0 * * 0' # weekly (every Sunday)

  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # needed to allow julia-actions/cache to delete old caches that it has created
      contents: write # needed for Quarto render
    steps:
      - uses: actions/checkout@v7
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
        with:
          precompile: true
      - name: Fix Timestamps
        run: bash .github/scripts/fix-timestamps
      - name: Quarto Render
        uses: quarto-dev/quarto-actions/render@v2
      - name: Checkout notebooks branch
        uses: actions/checkout@v7
        with:
          ref: notebooks
          path: _output/branch-out
          fetch-depth: 0
      - name: Remove stale notebooks
        run: |
          pushd _output/branch-out
          git ls-files "*.ipynb" | while read ipynb; do
            src="../${ipynb%.ipynb}.qmd"
            if [ ! -f "$src" ]; then
              git rm --ignore-unmatch "$ipynb"
            fi
          done
          popd
      - name: Copy artifacts
        run: |
          # helper files at root
          cp Project.toml apt.txt postBuild _output/branch-out/
          cp -r .jupyter _output/branch-out/

          pushd _output

          rsync -avc --exclude='branch-out/' --include='*/' --include='*.ipynb' --exclude='*'  --prune-empty-dirs ./ branch-out/

          popd
      - name: Commit & Push to notebooks branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pushd _output/branch-out
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to push"
          else
            git commit -m "Update notebooks from ${{ github.sha }}"
            git push origin notebooks
          fi
          popd
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _output/
          clean-exclude: pr-preview/
          force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
